modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="mtools" #mandatory
version="alpha-1.0.0" #mandatory
displayName="More Tools Mod" #mandatory
updateJSONURL="" #optional
displayURL="" #optional
logoFile="" #optional
credits="Thanks to the painstaking process of mining 3x3 tunnel, I came up with this idea" #optional
authors="xxMrPHDxx" #optional
description="This mod adds more tools. Hurray!"
[[dependencies.mtools]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.mtools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
